config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('dogs.urls', namespace='dogs')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.apps import DogsConfig

from dogs.views import index, breeds_list_view, breed_dogs_list_view, dogs_list_view, dog_create_view, dog_detail_view, dog_update_view, dog_delete_view

app_name = DogsConfig.name

urlpatterns = [
    # breeds
    path('', index, name='index'),
    path('breeds/', breeds_list_view, name = 'breeds'),
    
    #dogs
    path('breeds/<int:pk>/dogs/', breed_dogs_list_view, name='breed_dogs'),
    path('dogs/', dogs_list_view, name='dogs_list'),
    path('dogs/create/', dog_create_view, name='dog_create'),
    path('dogs/detail/<int:pk>/', dog_detail_view, name='dog_detail'),
    path('dogs/update/<int:pk>', dog_update_view, name='dog_update'),
    path('dogs/delete/<int:pk>', dog_delete_view, name='dog_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_register_view, user_login_view, user_profile_view, user_logout_view, \
                        user_update_view, user_change_password_view, user_generate_new_password_view

app_name = UsersConfig.name

urlpatterns = [
    path('', user_login_view, name = 'user_login'),
    path('logout/', user_logout_view, name = 'user_logout'),
    path('register/', user_register_view, name='user_register'),
    path('profile/', user_profile_view, name='user_profile'),
    path('update/', user_update_view, name='user_update'),
    path('change_password/', user_change_password_view, name='user_change_password'),
    path('profile/genpassword/', user_generate_new_password_view, name='user_generate_new_password'),
]

dogs/models.py
from django.db import models
from django.conf import settings

from users.models import NULLABLE


class Breed(models.Model):
    name = models.CharField(max_length=100, verbose_name='Порода')
    description = models.CharField(max_length=1000, verbose_name='Описание')
    
    def __str__(self):
        return f'{self.name}'
    
    class Meta:
        verbose_name = 'breed'
        verbose_name_plural = 'breeds'
        
class Dog(models.Model):
    name = models.CharField(max_length=250, verbose_name='Кличка')
    breed = models.ForeignKey(Breed, on_delete=models.CASCADE, verbose_name='Порода')
    photo = models.ImageField(upload_to='dogs/', **NULLABLE, verbose_name='Фотография')
    birth_date = models.DateField(**NULLABLE, verbose_name='Дата рождения')
    
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='Хозяин')
        
    def __str__(self):
        return f'{self.name} ({self.breed})'
    
    
    class Meta:
        verbose_name = 'dog'
        verbose_name_plural = 'dogs'
        
        # abstract = True
        # app_label = 'dogs'
        # ordering = [-1]
        # proxy = True
        # permissions = []
        # db_table = 'doggies'
        # get_latest_by = 'birth_date'

dogs/forms.py
import datetime

from django import forms

from dogs.models import Dog
from users.forms import StyleFormMixin


class DogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Dog
        exclude = ('owner', )
        
    def clean_birth_date(self):
        cleaned_data = self.cleaned_data['birth_date']
        now_year = datetime.datetime.now().year
        if now_year - cleaned_data.year > 35:
            raise forms.ValidationError('Собака должна быть моложе 35 лет')
        return cleaned_data
        

dogs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from dogs.models import Breed, Dog
from dogs.forms import DogForm


def index(request):
    context = {
        'objects_list': Breed.objects.all()[:3],
        'title': 'Питомник - Главная',
    }
    return render(request, 'dogs/index.html', context=context)


def breeds_list_view(request):
    context = {
        'objects_list': Breed.objects.all(),
        'title': 'Питомник - Все наши породы',
    }
    return render(request, 'dogs/breeds.html', context=context)


# список собак конкретной породы
def breed_dogs_list_view(request, pk: int):
    breed_object = Breed.objects.get(pk=pk)
    context = {
        'objects_list': Dog.objects.filter(breed_id=pk),
        'title': f'Собаки породы - {breed_object.name}',
        'breed_pk': breed_object.pk,
    }
    return render(request, 'dogs/dogs.html', context=context)


def dogs_list_view(request):
    context = {
        'objects_list': Dog.objects.all,
        'title': f'Все наши собаки',
    }
    return render(request, 'dogs/dogs.html', context)


# Create Read Update Delet (CRUD)
@login_required(login_url='users:user_login')
def dog_create_view(request):
    if request.method == 'POST':
        form = DogForm(request.POST, request.FILES)
        if form.is_valid():
            dog_object = form.save()
            dog_object.owner = request.user
            dog_object.save()
            return HttpResponseRedirect(reverse('dogs:dogs_list'))
    context = {
        'title': "Добавить собаку",
        'form': DogForm,
    }
    return render(request, 'dogs/create_update.html', context=context)


@login_required(login_url='users:user_login')
def dog_detail_view(request, pk):
    dog_object = Dog.objects.get(pk=pk)
    context = {
        'object': dog_object,
        'title': dog_object
    }
    return render(request, 'dogs/detail.html', context=context)


@login_required(login_url='users:user_login')
def dog_update_view(request, pk):
    dog_object = get_object_or_404(Dog, pk=pk)
    if request.method =="POST":
        form = DogForm(request.POST, request.FILES, instance=dog_object)
        if form.is_valid():
            dog_object = form.save()
            dog_object.save()
            return HttpResponseRedirect(reverse('dogs:dog_detail', args={pk: pk}))
    context = {
        'object': dog_object,
        'title': 'Изменить собаку',
        'form': DogForm(instance=dog_object)
    }
    return render(request, 'dogs/create_update.html', context=context)


@login_required(login_url='users:user_login')
def dog_delete_view(request, pk):
    dog_object = get_object_or_404(Dog, pk=pk)
    if request.method =="POST":
        dog_object.delete()
        return HttpResponseRedirect(reverse('dogs:dogs_list'))
    context = {
        'object': dog_object,
        'title': 'Удалить собаку'
    }
    return render(request, 'dogs/delete.html', context=context)

dogs/templates/dogs/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Add some information about the album below, the author, or any other
                        background context. Make it a few sentences long so folks can pick up some informative tidbits.
                        Then, link them off to some social networking sites or contact information.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'dogs:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'dogs:breeds' %}" class="text-white">Породы</a></li>
                        <li><a href="{% url 'dogs:dogs_list' %}" class="text-white">Собаки</a></li>
                        <li><a href="{% url 'dogs:dog_create' %}" class="text-white">Добавить собаку</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'users:user_profile' %}" class="text-white">Профиль</a></li>
                            <li><a href="{% url 'users:user_logout' %}" class="text-white">Выход</a></li>
                        {% else %}
                            <li><a href="{% url 'users:user_login' %}" class="text-white">Вход</a></li>
                            <li><a href="{% url 'users:user_register' %}" class="text-white">Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Питомник</strong>
                {% if user.is_authenticated %}
                <span style="margin-left:100px"  class="text-white">{{ user }}</span>
                {% endif %}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

dogs/templates/dogs/breeds.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    {% for object in objects_list %}
        {% include 'dogs/includes/inc_breed.html' with object=object%}
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/create.html
{% extends 'dogs/base.html' %}

{% block content %}
<form method="post" enctypy="multipart/from-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Введите данные собаки
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-succes">
                    Добавить
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/create_update.html
{% extends 'dogs/base.html' %}
{% load my_tags %}

{% block content %}
<form method="post" enctypy="multipart/from-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Обновите данные собаки
                {% else  %}
                Введите данные собаки
                {% endif %}
            </div>
            <img class="card-img-top" 
                    src="{{ object.photo|dogs_media }}" width="300" height="400"
                    alt="Card image cap">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else  %}
                    Добавить
                    {% endif %}
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

dogs/templates/dogs/delete.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<form method="POST" enctype="multipart/from-data" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Вы уверены, что хотите удалить собаку?
                {% endif %}
            </div>
            <div class="card-body">
                <img class="card-img-top" 
                    src="{{ object.photo|dogs_media }}" width="300" height="320"
                    alt="Card image cap">
            
                <div class="card-body">
                    <p class="card-text"> {{ object.name|title }}</p>
                </div>
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-danger float-right">
                    {% if object %}
                    Удалить
                    {% endif %}
                </button>
                <a class="btn btn-outline-primary float-left" href="{% url 'dogs:dog_detail' object.pk %}">Назад</a>
            </div>
        </div>
    </div>
</form>

{% endblock %}

dogs/templates/dogs/detail.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <img class="card-img-top" 
                 src="{{ object.photo|dogs_media }}" width="300" height="320"
                 alt="Card image cap">
        <div class="card-body">
            <p class="card-text">Кличка: {{ object.name }}</p>
            <p class="card-text">Порода: {{ object.breed.name }}</p><br>
            <span class="text-muted">Дата рождения: {{ object.birth_date|default:"-" }}</span><br>
            <span class="text-muted">Электронная почта хозяина: {{ object.owner|default:"Без хозяина" }}</span><br>
            <span class="text-muted">Имя хозяина: {{ object.owner.first_name|default:"Не указано" }}</span><br>
            <span class="text-muted">Телефон хозяина: {{ object.owner.phone|default:"Не указано" }}</span><br>
            <span class="text-muted">Телеграм хозяина: {{ object.owner.telegram|default:"Не указано" }}</span><br>
        </div>
        <div class="card-footer">
            <a class="btn btn-link" href="{% url 'dogs:dog_update' object.pk %}">обновить</a>
            <a class="btn btn-link" href="{% url 'dogs:dog_delete' object.pk %}">удалить</a>
        </div>
    </div>
</div>    
{% endblock %}

dogs/templates/dogs/dogs.html
{% extends 'dogs/base.html' %}
{% load my_tags %}
{% block content %}

<div class="row">
    {% for object in objects_list %}
    <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <img class="card-img-top" 
                 src="{{ object.photo|dogs_media }}" width="300" height="320"
                 alt="Card image cap">
            <div class="card-body">
                <p class="card-text">{{ object.name|title }}</p>
            </div>
            <div class="card-footer">
                <a class="btn btn-link" href="{% url 'dogs:dog_detail' object.pk %}">Подробнее</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

dogs/templates/dogs/index.html
{% extends 'dogs/base.html' %}

{% block content %}
<div class="row">
    {% for object in objects_list %}
        {% include 'dogs/includes/inc_breed.html' with object=object %}
    {% endfor %}
</div>
{% endblock %}