config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('dogs.urls', namespace='dogs')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dogs/urls.py
from django.urls import path
from dogs.apps import DogsConfig

from dogs.views import index, breeds_list_view, breed_dogs_list_view, dogs_list_view, dog_create_view, dog_detail_view, dog_update_view, dog_delete_view

app_name = DogsConfig.name

urlpatterns = [
    # breeds
    path('', index, name='index'),
    path('breeds/', breeds_list_view, name = 'breeds'),
    
    #dogs
    path('breeds/<int:pk>/dogs/', breed_dogs_list_view, name='breed_dogs'),
    path('dogs/', dogs_list_view, name='dogs_list'),
    path('dogs/create/', dog_create_view, name='dog_create'),
    path('dogs/detail/<int:pk>/', dog_detail_view, name='dog_detail'),
    path('dogs/update/<int:pk>', dog_update_view, name='dog_update'),
    path('dogs/delete/<int:pk>', dog_delete_view, name='dog_delete'),
]

users/urls.py
from django.urls import path

from users.apps import UsersConfig
from users.views import user_register_view, user_login_view, user_profile_view, user_logout_view, \
                        user_update_view, user_change_password_view, user_generate_new_password_view

app_name = UsersConfig.name

urlpatterns = [
    path('', user_login_view, name = 'user_login'),
    path('logout/', user_logout_view, name = 'user_logout'),
    path('register/', user_register_view, name='user_register'),
    path('profile/', user_profile_view, name='user_profile'),
    path('update/', user_update_view, name='user_update'),
    path('change_password/', user_change_password_view, name='user_change_password'),
    path('profile/genpassword/', user_generate_new_password_view, name='user_generate_new_password'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# не всегда так можно делать
NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    first_name = models.CharField(max_length=250, verbose_name='Имя', default='Anonymous')
    last_name = models.CharField(max_length=250, verbose_name='Фамилия', default='Anonymous')
    phone = models.CharField(max_length=35, unique=True, verbose_name='Телефон', **NULLABLE)
    telegram = models.CharField(max_length=150, unique=True, verbose_name='Телеграм', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)
    is_active = models.BooleanField(default=True,  verbose_name='Активность')
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    
    def __str__(self):
        return f'{self.email}'
    
    
    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['id']
        
        
    

users/forms.py
from django import forms

from users.models import User
from users.validators import validate_password
from django.contrib.auth.forms import PasswordChangeForm

class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class  UserForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone',)


class UserRegisterForm(StyleFormMixin, forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('email',)
        
    def clean_password2(self):
        cleaned_data = self.cleaned_data
        validate_password(cleaned_data['password'])
        if cleaned_data['password'] != cleaned_data['password2']:
            print('Пароли не совпадают')
            raise forms.ValidationError('Пароли не совпадают!!!')
        return cleaned_data['password2']
    
    
    
class UserLoginForm(StyleFormMixin, forms.Form):
    email = forms.EmailField()
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    
    
class  UserUpdateForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'telegram', 'avatar',)
        

class UserChangePasswordForm(StyleFormMixin, PasswordChangeForm):
    pass

users/views.py
import random
import string

from django.shortcuts import render, reverse, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from users.forms import UserRegisterForm, UserLoginForm, UserUpdateForm, UserChangePasswordForm
from users.services import send_register_email, send_new_password


def user_register_view(request):
    form = UserRegisterForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            new_user = form.save() # создаем пользователя
            print(form.cleaned_data['password'])
            new_user.set_password(form.cleaned_data['password']) # хэшируем пароль пользователя
            new_user.save() # сохраняем пользователя в базу
            send_register_email(new_user.email)
            return HttpResponseRedirect(reverse('dogs:index'))
    context = {
        'title': 'Создать аккаунт',
        'form': UserRegisterForm
    }
    return render(request, 'users/user_register.html', context=context)


def user_login_view(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = authenticate(email=cleaned_data['email'], password=cleaned_data['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('dogs:index'))
            return HttpResponse('Вы не зарегистрированы либо неверный пароль, либо вы забанены!')
    context = {
        'title': 'Вход в аккаунт',
        'form': UserLoginForm
    }
    return render(request, 'users/user_login.html', context=context)


@login_required(login_url='users:user_login')
def user_profile_view(request):
    user_object = request.user
    if user_object.first_name and user_object.last_name:
        user_name = user_object.first_name + ' ' + user_object.last_name
    else:
        user_name = "Anonymous"
    context = {
        'title': f'Ваш профиль {user_name}',
    }
    return render(request, 'users/user_profile_read_only.html', context=context)


@login_required(login_url='users:user_login')
def user_update_view(request):
    user_object = request.user
    if request.method == "POST":
        form = UserUpdateForm(request.POST, request.FILES, instance=user_object)
        if form.is_valid():
            user_object = form.save()
            user_object.save()
            return HttpResponseRedirect(reverse('users:user_profile'))
    context = {
        'object': user_object,
        'title': f'Изменить профиль {user_object.first_name} {user_object.last_name}',
        'form': UserUpdateForm(instance=user_object)
    }
    return render(request, 'users/user_update.html', context=context)
    
@login_required(login_url='users:user_login')
def user_change_password_view(request):
    user_object = request.user
    form = UserChangePasswordForm(user_object, request.POST)
    if request.method == "POST":
        if form.is_valid():
            user_object = form.save()
            update_session_auth_hash(request, user_object)
            messages.success(request, 'Пароль было успешно изменен')
            return HttpResponseRedirect(reverse('users:user_profile'))
        else:
            messages.error(request, 'Не удалось изменить пароль')
    context = {
        'title': f'Изменить профиль {user_object.first_name} {user_object.last_name}',
        'form': form,
    }
    return render(request, 'users/user_change_password.html', context=context)
    



@login_required(login_url='users:user_login')
def user_logout_view(request):
    logout(request)
    return redirect('dogs:index')



@login_required(login_url='users:user_login')
def user_generate_new_password_view(request):
    new_password = ''.join(random.sample((string.ascii_letters + string.digits), 12))
    request.user.set_password(new_password)
    request.user.save()
    send_new_password(request.user.email, new_password)
    return redirect(reverse('dogs:index'))

users/templates/users/user_change_password.html
{% extends "dogs/base.html" %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Изменение пароля
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success float-right">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_login.html
{% extends "dogs/base.html" %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Введите данные для входа в аккаунт</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success float-left">Вход</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_profile_read_only.html
{% extends "dogs/base.html" %}
{% load my_tags %}
{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Мой профиль</div>
            <img class="card-img-top"
                 src="{{ user.avatar|user_media }}" width="300" height="700"
                 alt="Card img cap">
            <div class="card-body">
                <span class="card-text">Email: {{user.email}}</span><br>
                <span class="card-text">Имя: {{user.first_name|default:"не указано"}}</span><br>
                <span class="card-text">Фамилия: {{user.last_name|default:"не указано"}}</span><br>
                <span class="card-text">Телефон: {{user.phone|default:"не указано"}}</span><br>
                <span class="card-text">Телеграм: {{user.telegram|default:"не указано"}}</span><br>
                <button class="btn btn-outline-warning">
                    <a class="btn btn-link" href="{% url 'users:user_update' %}">обновить</a>
                </button>
                <button class="btn btn-outline-warning">
                    <a class="btn btn-link" href="{% url 'users:user_change_password' %}">измнить пароль</a>
                </button>
                <button class="btn btn-outline-danger">
                    <a class="btn btn-link" href="{% url 'users:user_generate_new_password' %}">генерация пароля</a>
                </button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_register.html
{% extends "dogs/base.html" %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="cord-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success float-right">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/user_update.html
{% extends "dogs/base.html" %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Изменить профиль
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success float-right">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}